<?xml version="1.0"?>
<robot name="micromouse" xmlns:xacro="https://www.ros.org/wiki/xacro">

    <material name="body_texture">
        <color rgba="0.2 0.4 0.2 1.0"/>
    </material>

    <material name="black">
        <color rgba="0.0 0.0 0.0 1.0"/>
    </material>
    
    <xacro:property name="rotate_90" value="1.57079632679"/>
    <xacro:property name="head_radius" value="0.025"/>
    <xacro:property name="body_radius" value="0.020"/>
    <xacro:property name="body_length" value="0.07"/>

    <xacro:macro name="default_inertial">
        <inertial>
            <mass value="0.001" />
            <inertia ixx="1e-06" ixy="0.0" ixz="0.0" iyy="1e-06" iyz="0.0" izz="1e-06" />
        </inertial>
    </xacro:macro>
    
    <link name="base_link"/>
    <link name="mouse_body_link">
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <mass value="0.5"/>
            <inertia ixx="0.00022083" ixy="0.0" ixz="0.0" iyy="0.00022083" iyz="0.0" izz="0.00040833"/>
        </inertial>
        <visual name="body">
            <origin xyz="0.0 0.0 0.0" rpy="${rotate_90} 0.0 0.0"/>
            <geometry>
                <cylinder radius="${body_radius}" length="${body_length}"/>
            </geometry>
            <material name="body_texture"/>
        </visual>
        <collision name="body">
            <origin xyz="0.0 0.0 0.0" rpy="${rotate_90} 0.0 0.0"/>
            <geometry>
                <cylinder radius="${body_radius}" length="${body_length}"/>
            </geometry>
        </collision>
        <visual name="left_base">
            <geometry>
                <box size="0.005 0.06 0.02"/>
            </geometry>
            <material name="body_texture"/>
        </visual>
        <collision name="left_base">
            <geometry>
                <box size="0.005 0.06 0.02"/>
            </geometry>
            <material name="body_texture"/>
        </collision>
    </link>

    <joint name="dummy_joint" type="fixed">
        <parent link="base_link"/>
        <child link="mouse_body_link"/>
    </joint>

    <link name="mouse_head_link">
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <mass value="0.2"/>
            <inertia ixx="0.00015" ixy="0.0" ixz="0.0" iyy="0.00015" iyz="0.0" izz="0.00015"/>
        </inertial>
        <visual name="head">
            <origin xyz="0.0 ${body_length/2} 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <sphere radius="${head_radius}"/>
            </geometry>
            <material name="body_texture"/>
        </visual>
        <collision name="head">
            <origin xyz="0.0 ${body_length/2} 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <sphere radius="${head_radius}"/>
            </geometry>
        </collision>
    </link>

    <joint name="mouse_head_joint" type="revolute">
        <parent link="mouse_body_link"/>
        <child link="mouse_head_link"/>
        <axis xyz="0 0 1"/>
        <limit lower="-${rotate_90/8}" upper="${rotate_90/8}" velocity="5.0" effort="10.0"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>


    <link name="mouse_left_eye_link">
        <visual>
            <origin xyz="-0.01 0.05 0.01"/>
            <geometry>
                <sphere radius="0.001"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="-0.01 0.05 0.01"/>
            <geometry>
                <sphere radius="0.001"/>
            </geometry>
        </collision>
        <xacro:default_inertial/>
    </link>

    <joint name="left_eye_joint" type="fixed">
        <parent link="mouse_head_link"/>
        <child link="mouse_left_eye_link"/>
    </joint>

    <link name="mouse_right_eye_link">
        <visual>
            <origin xyz="0.01 0.05 0.01"/>
            <geometry>
                <sphere radius="0.001"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0.01 0.05 0.01"/>
            <geometry>
                <sphere radius="0.001"/>
            </geometry>
        </collision>
        <xacro:default_inertial/>
    </link>

    <joint name="right_eye_joint" type="fixed">
        <parent link="mouse_head_link"/>
        <child link="mouse_right_eye_link"/>
    </joint>
    
    
</robot>