micromouse:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: "joint_state_controller/JointStateController"
    publish_rate: 50
  
  # Position Controllers ---------------------------------------
  base_to_left_wheel_joint_position_controller:
    type: "position_controllers/JointPositionController"
    joint: left_wheel
    pid: {p: 100.0, i: 0.01, d: 10.0}

  base_to_right_wheel_joint_position_controller:
    type: "position_controllers/JointPositionController"
    joint: right_wheel
    pid: {p: 100.0, i: 0.01, d: 10.0}