obstacle_range: 6.0
raytrace_range: 8.5

footprint: [[0.20, 0.19], [0.20, -0.19], [-0.20, -0.19], [-0.20, 0.19]]

publish_frequency: 1.0

inflation_layer:
  inflation_radius: 0.55
  cost_scaling_factor: 10

obstacles_layer:
  observation_sources: scan
  scan: {data_type: LaserScan, topic: ebot/laser/scan, marking: true, clearing: true}
  
static:
  map_topic: map
  subscribe_to_updates: true
  

    



