DWAPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 0.70 
  min_vel_x: 0.0

  max_vel_y: 0.0  
  min_vel_y: 0.0  

  max_trans_vel: 0.70 
  min_trans_vel: 0.1  
  trans_stopped_vel: 0.1

  max_rot_vel: 1.5  
  min_rot_vel: -1.5 
  rot_stopped_vel: 0.0

  acc_lim_x: 1.0 
  acc_lim_theta: 4.5
  acc_lim_y: 0.0      

# Goal Tolerance Parameters
  yaw_goal_tolerance: 6.14  # Since pose is not required this value is set to 2*pi
  xy_goal_tolerance: 0.10  
  latch_xy_goal_tolerance: false

# Forward Simulation Parameters
  sim_time: 1.20 
  vx_samples: 40       
  vy_samples: 1       
  vtheta_samples: 20  

# Trajectory Scoring Parameters
  path_distance_bias: 84.0      
  goal_distance_bias: 24.0      
  occdist_scale: 0.5            
  forward_point_distance: 0.325 
  stop_time_buffer: 0.2         
  scaling_speed: 0.25           
  max_scaling_factor: 0.2       

# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05  

# Debugging
  publish_traj_pc : true
  publish_cost_grid_pc: true
  global_frame_id: odom

  holonomic_robot: false