global_costmap:
  global_frame: map
  robot_base_frame: ebot_base
  update_frequency: 1.0 
  publish_frequency: 0.5 
  static_map: true
  transform_tolerance: 0.5
  
  plugins:
  - {name: static,                  type: "costmap_2d::StaticLayer"}
  - {name: obstacles_layer,         type: "costmap_2d::VoxelLayer"}
  - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}
 
  