local_costmap:
  global_frame: odom
  robot_base_frame: ebot_base
  update_frequency: 5.0
  publish_frequency: 2.0 
  static_map: false
  rolling_window: true
  width: 4.0
  height: 4.0
  resolution: 0.05
  transform_tolerance: 0.50 
  footprint_padding: 0.0
  
  plugins:
  - {name: obstacles_layer,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer,           type: "costmap_2d::InflationLayer"}